export type UnitTypes =
        "spear"
        | "sword"
        | "axe"
        | "archer"
        | "light_cavalry"
        | "mounted_archer"
        | "heavy_cavalry"
        | "ram"
        | "catapult"
        | "knight"
        | "snob"
        | "trebuchet"
        | "doppelsoldner"

export type Building =
        "headquarter"
        | "barracks"
        | "tavern"
        | "hospital"
        | "preceptory"
        | "chapel"
        | "church"
        | "academy"
        | "rally_point"
        | "statue"
        | "market"
        | "timber_camp"
        | "clay_pit"
        | "iron_mine"
        | "farm"
        | "warehouse"
        | "wall"

export type Officer = "leader" | "loot_master" | "medic" | "scout" | "supporter" | "bastard"